Repository ryanjulian/rllab, pull requests merged in 2018-05, with the labels that each got.

#59 Add TensorFlow GPU v1.8 during the setup of the virtual env (#9)
  environment.yml
  scripts/setup_linux.sh
Labels: good first issue

#88 Add save graph and tensor logging to tensorboard
  rllab/misc/logger.py
  rllab/misc/tensorboard_output.py
Labels: feature

#91 Refactor rllab from rllab.mujoco_py to mujoco_py (v1.5.0)
  environment.yml
  examples/trpo_cartpole.py
  examples/trpo_swimmer.py
  rllab/algos/batch_polopt.py
  rllab/envs/mujoco/ant_env.py
  rllab/envs/mujoco/gather/embedded_viewer.py
  rllab/envs/mujoco/gather/gather_env.py
  rllab/envs/mujoco/half_cheetah_env.py
  rllab/envs/mujoco/hopper_env.py
  rllab/envs/mujoco/inverted_double_pendulum_env.py
  rllab/envs/mujoco/maze/maze_env.py
  rllab/envs/mujoco/mujoco_env.py
  rllab/envs/mujoco/point_env.py
  rllab/envs/mujoco/simple_humanoid_env.py
  rllab/envs/mujoco/swimmer_env.py
  rllab/envs/mujoco/walker2d_env.py
  rllab/envs/occlusion_env.py
  rllab/mujoco_py/.rvmrc
  rllab/mujoco_py/Gemfile
  rllab/mujoco_py/Gemfile.lock
  rllab/mujoco_py/__init__.py
  rllab/mujoco_py/codegen.rb
  rllab/mujoco_py/gen_binding.sh
  rllab/mujoco_py/glfw.py
  rllab/mujoco_py/mjconstants.py
  rllab/mujoco_py/mjcore.py
  rllab/mujoco_py/mjextra.py
  rllab/mujoco_py/mjlib.py
  rllab/mujoco_py/mjtypes.py
  rllab/mujoco_py/mjviewer.py
  rllab/mujoco_py/util.py
  rllab/plotter/plotter.py
  sandbox/rocky/tf/launchers/trpo_cartpole.py
  scripts/setup_mujoco.sh
  scripts/sim_env.py
  tests/envs/test_envs.py
Labels: big, housecleaning

#58 add tensorboard Histogram
  examples/example_tensorboard_logger.py
  rllab/misc/logger.py
  rllab/misc/tensorboard_summary.py
Labels: feature
